//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2017.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2017.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18144568296689784866596347266193986531397687719431268499352125948651752796139671756185482545396318113437957491837321373218469774666839963164262237368442532611258528394646232336399175389564717779769121478414921519871598694757366898718874687867839962453379255165133597984713197596567795775557135893466532748728731246777118798142478551478542178178197647732671267431199473594798738351669989791659543322829419875971595946957876673951847511877175578719623877234576294147735948345664119468533352832958111378859984362132 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day1 {
            get {
                return ResourceManager.GetString("Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s,se,se,se,s,sw,s,s,s,nw,se,sw,sw,sw,sw,nw,sw,nw,sw,nw,nw,nw,nw,nw,n,nw,sw,ne,n,nw,nw,s,n,n,n,n,n,n,se,sw,ne,n,ne,n,s,ne,n,n,ne,ne,ne,n,n,ne,nw,ne,n,ne,s,se,ne,ne,ne,ne,ne,se,ne,se,se,ne,ne,ne,ne,se,ne,se,ne,ne,n,se,se,ne,ne,ne,se,sw,ne,ne,se,se,ne,se,se,se,se,se,s,se,se,ne,se,se,se,se,se,ne,se,s,se,se,se,nw,nw,n,s,se,s,se,se,s,se,se,s,s,se,s,se,s,s,s,s,se,se,nw,ne,s,s,s,s,s,s,sw,s,s,nw,s,s,s,nw,s,s,s,s,s,s,sw,ne,sw,s,sw,nw,s,s,s,n,s,s,s,s,s,sw,s,s,sw,sw,s,nw,ne,sw,s,se,sw,s,s,sw,se,sw,sw,s,sw,sw,s,sw,sw,sw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 &lt;-&gt; 396, 1867
        ///1 &lt;-&gt; 1749
        ///2 &lt;-&gt; 466, 675, 1661
        ///3 &lt;-&gt; 3, 328, 1160
        ///4 &lt;-&gt; 4, 953
        ///5 &lt;-&gt; 1922
        ///6 &lt;-&gt; 1273
        ///7 &lt;-&gt; 7, 959
        ///8 &lt;-&gt; 96, 274
        ///9 &lt;-&gt; 9, 1036
        ///10 &lt;-&gt; 1783
        ///11 &lt;-&gt; 879
        ///12 &lt;-&gt; 382, 1390
        ///13 &lt;-&gt; 1214, 1473
        ///14 &lt;-&gt; 434, 508, 1470
        ///15 &lt;-&gt; 324, 747
        ///16 &lt;-&gt; 195, 894
        ///17 &lt;-&gt; 536
        ///18 &lt;-&gt; 1024, 1198
        ///19 &lt;-&gt; 1616
        ///20 &lt;-&gt; 797
        ///21 &lt;-&gt; 885
        ///22 &lt;-&gt; 1001
        ///23 &lt;-&gt; 569, 1496
        ///24 &lt;-&gt; 392
        ///25 &lt;-&gt; 32
        ///26 &lt;-&gt; 820
        ///27 &lt;-&gt; 655
        ///28 &lt;-&gt; 1044
        ///29 &lt;-&gt; 307, 675, 1518
        ///30 &lt;-&gt; 1547, 1775, 1885
        ///31 &lt;-&gt; 237
        ///32 &lt;-&gt; 25, 1736
        ///33 &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0: 3
        ///1: 2
        ///2: 4
        ///4: 4
        ///6: 5
        ///8: 8
        ///10: 6
        ///12: 6
        ///14: 6
        ///16: 6
        ///18: 8
        ///20: 8
        ///22: 12
        ///24: 10
        ///26: 9
        ///28: 8
        ///30: 8
        ///32: 12
        ///34: 12
        ///36: 12
        ///38: 12
        ///40: 8
        ///42: 12
        ///44: 14
        ///46: 14
        ///48: 10
        ///50: 12
        ///52: 12
        ///54: 14
        ///56: 14
        ///58: 14
        ///62: 12
        ///64: 14
        ///66: 14
        ///68: 14
        ///70: 12
        ///74: 14
        ///76: 14
        ///78: 14
        ///80: 18
        ///82: 17
        ///84: 30
        ///88: 14.
        /// </summary>
        internal static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x15/10,ph/c,x3/14,s1,pf/b,x12/0,ph/m,x14/11,s4,x6/13,s2,x7/14,pn/f,x1/9,s7,x14/11,s9,x15/6,s14,x0/5,s1,x6/7,pp/i,s8,x4/3,s5,x15/6,s3,x4/3,s13,x11/6,pf/m,x13/5,s9,x0/3,s13,x15/5,pl/h,s1,x9/0,pf/a,x12/4,s5,x15/10,pn/i,x9/14,pm/l,x10/6,s8,x14/5,s6,x9/11,s2,x8/0,s6,x7/14,s2,x10/15,s1,x11/13,pf/b,x12/8,s8,pd/j,x1/13,s9,x3/6,s13,x2/8,s9,pp/e,x6/14,pm/b,x13/12,s6,x10/4,s10,x5/1,pi/a,x9/15,s8,x10/11,ph/j,x7/3,s9,x4/2,pb/g,x14/13,s10,x8/11,s11,x6/14,s10,x4/7,s6,x13/1,pn/k,s12,x9/7,pl/e,x2/13,s9,x10/9,po/c,x7/2,s4,x3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day16 {
            get {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set i 31
        ///set a 1
        ///mul p 17
        ///jgz p p
        ///mul a 2
        ///add i -1
        ///jgz i -2
        ///add a -1
        ///set i 127
        ///set p 316
        ///mul p 8505
        ///mod p a
        ///mul p 129749
        ///add p 12345
        ///mod p a
        ///set b p
        ///mod b 10000
        ///snd b
        ///add i -1
        ///jgz i -9
        ///jgz a 3
        ///rcv b
        ///jgz b -1
        ///set f 0
        ///set i 126
        ///rcv a
        ///rcv b
        ///set p a
        ///mul p -1
        ///add p b
        ///jgz p 4
        ///snd a
        ///set a b
        ///jgz 1 3
        ///snd b
        ///set f 1
        ///add i -1
        ///jgz i -11
        ///snd a
        ///jgz f -16
        ///jgz a -19.
        /// </summary>
        internal static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                                              |                                                                                                                           
        ///             +-------+       +-------+   +-+                                 | +-------------------------------------------+                   +---------------+     +-+ +---------------------------+   
        ///             |       |       |       |   | |                                 | |                           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day19 {
            get {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3458	3471	163	1299	170	4200	2425	167	3636	4001	4162	115	2859	130	4075	4269
        ///2777	2712	120	2569	2530	3035	1818	32	491	872	113	92	2526	477	138	1360
        ///2316	35	168	174	1404	1437	2631	1863	1127	640	1745	171	2391	2587	214	193
        ///197	2013	551	1661	121	206	203	174	2289	843	732	2117	360	1193	999	2088
        ///3925	3389	218	1134	220	171	1972	348	3919	3706	494	3577	3320	239	120	2508
        ///239	947	1029	2024	733	242	217	1781	2904	2156	1500	3100	497	2498	3312	211
        ///188	3806	3901	261	235	3733	3747	3721	267	3794	3814	3995	3004	915	4062	340 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day2 {
            get {
                return ResourceManager.GetString("Day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p=&lt;2366,784,-597&gt;, v=&lt;-12,-41,50&gt;, a=&lt;-5,1,-2&gt;
        ///p=&lt;-2926,-3402,-2809&gt;, v=&lt;-55,65,-16&gt;, a=&lt;11,4,8&gt;
        ///p=&lt;2290,257,-3040&gt;, v=&lt;41,119,57&gt;, a=&lt;-10,-10,5&gt;
        ///p=&lt;3090,-493,-1340&gt;, v=&lt;-134,19,-37&gt;, a=&lt;1,0,7&gt;
        ///p=&lt;-1338,2295,4101&gt;, v=&lt;-158,34,-48&gt;, a=&lt;19,-12,-12&gt;
        ///p=&lt;-1140,1657,-981&gt;, v=&lt;17,-75,45&gt;, a=&lt;3,0,0&gt;
        ///p=&lt;1544,40,141&gt;, v=&lt;-59,33,-75&gt;, a=&lt;-1,-3,6&gt;
        ///p=&lt;3711,-950,-574&gt;, v=&lt;-8,55,61&gt;, a=&lt;-14,-1,-3&gt;
        ///p=&lt;1643,-235,-1267&gt;, v=&lt;-52,11,35&gt;, a=&lt;-2,0,2&gt;
        ///p=&lt;2501,-4492,4189&gt;, v=&lt;-68,124,-75&gt;, a=&lt;-4,7,-10&gt;
        ///p=&lt;-2141,-48,2297&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..######.###...######...#
        ///.##..##.#....#..##.#....#
        ///.##.#....###..##.###.#.#.
        ///#.#.###.#####.###.##.##.#
        ///.###.#.#.###.####..##.###
        ///..####.##..#.#.#####...##
        ///....##.###..#.#..#...####
        ///.#.##.##.#..##...##.###..
        ///.######..#..#.#####....##
        ///###.##.###.########...###
        ///.#.#.#..#.##.#..###...#..
        ///.#.##.#.####.#.#.....###.
        ///##..###.###..##...#.##.##
        ///##.#.##..#...##...#...###
        ///##..#..###.#..##.#.#.#.#.
        ///.##.#####..##....#.#.#..#
        ///..#.######.##...#..#.##..
        ///#.##...#.#....###.#.##.#.
        ///.#..#.#.#..#.####..#.####        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set b 57
        ///set c b
        ///jnz a 2
        ///jnz 1 5
        ///mul b 100
        ///sub b -100000
        ///set c b
        ///sub c -17000
        ///set f 1
        ///set d 2
        ///set e 2
        ///set g d
        ///mul g e
        ///sub g b
        ///jnz g 2
        ///set f 0
        ///sub e -1
        ///set g e
        ///sub g b
        ///jnz g -8
        ///sub d -1
        ///set g d
        ///sub g b
        ///jnz g -13
        ///jnz f 2
        ///sub h -1
        ///set g b
        ///sub g c
        ///jnz g 2
        ///jnz 1 3
        ///sub b -17
        ///jnz 1 -23.
        /// </summary>
        internal static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42/37
        ///28/28
        ///29/25
        ///45/8
        ///35/23
        ///49/20
        ///44/4
        ///15/33
        ///14/19
        ///31/44
        ///39/14
        ///25/17
        ///34/34
        ///38/42
        ///8/42
        ///15/28
        ///0/7
        ///49/12
        ///18/36
        ///45/45
        ///28/7
        ///30/43
        ///23/41
        ///0/35
        ///18/9
        ///3/31
        ///20/31
        ///10/40
        ///0/22
        ///1/23
        ///20/47
        ///38/36
        ///15/8
        ///34/32
        ///30/30
        ///30/44
        ///19/28
        ///46/15
        ///34/50
        ///40/20
        ///27/39
        ///3/14
        ///43/45
        ///50/42
        ///1/33
        ///6/39
        ///46/44
        ///22/35
        ///15/20
        ///43/31
        ///23/23
        ///19/27
        ///47/15
        ///43/43
        ///25/36
        ///26/38
        ///1/10.
        /// </summary>
        internal static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin in state A.
        ///Perform a diagnostic checksum after 12459852 steps.
        ///
        ///In state A:
        ///  If the current value is 0:
        ///    - Write the value 1.
        ///    - Move one slot to the right.
        ///    - Continue with state B.
        ///  If the current value is 1:
        ///    - Write the value 1.
        ///    - Move one slot to the left.
        ///    - Continue with state E.
        ///
        ///In state B:
        ///  If the current value is 0:
        ///    - Write the value 1.
        ///    - Move one slot to the right.
        ///    - Continue with state C.
        ///  If the current value is 1:
        ///    - Write the va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oaoe rxeq vssdqtu xrk cjv yaoqp loo
        ///mveua dogbam szydvri hyzk lbega abzqw xwjn wniug kwbre
        ///npaoy uivpxwd oynpa rcdk uixpvdw
        ///yserir iikzcm ieuroca iuwcfov rvb giti crdpdcv mxpps
        ///spyuhgo lucasl ucllsa bymnjig yflbv nxitmlf
        ///xlxyhwz xla mpye fvjegwg fezlfrt inetrh vhg xpvstx ydhvq
        ///xgue cvtmh myg ontvvyw ygm oqzrdrw
        ///srdfsjf dli kccb kauk kauk apa doefc cdffkhh cdffkhh
        ///msizb elqiov lqn epamk onmnlst baawab ncafwaf jrataml iyzhy svycuec
        ///wdzqpcn dkgdumv wdzqpcn qxdmwib cjsigi bgcihgh fmua
        ///kpvbzf kpvbzf sv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day4 {
            get {
                return ResourceManager.GetString("Day4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2
        ///0
        ///-1
        ///2
        ///-2
        ///-3
        ///1
        ///-2
        ///0
        ///-8
        ///-1
        ///-7
        ///-8
        ///-11
        ///-7
        ///-8
        ///-7
        ///2
        ///-4
        ///-4
        ///-6
        ///-9
        ///0
        ///-20
        ///-7
        ///-16
        ///-10
        ///-25
        ///-3
        ///-17
        ///0
        ///2
        ///0
        ///-29
        ///-25
        ///-8
        ///-2
        ///-19
        ///0
        ///-38
        ///-29
        ///-5
        ///-24
        ///2
        ///-1
        ///-30
        ///0
        ///-28
        ///-43
        ///-22
        ///1
        ///-12
        ///-23
        ///-23
        ///-41
        ///-12
        ///-51
        ///-56
        ///-1
        ///-57
        ///-29
        ///-32
        ///-29
        ///-55
        ///1
        ///-28
        ///-29
        ///-49
        ///-56
        ///-13
        ///-67
        ///-40
        ///-10
        ///-44
        ///-32
        ///-37
        ///-49
        ///-37
        ///-72
        ///-54
        ///-22
        ///-24
        ///-31
        ///-26
        ///-45
        ///-45
        ///-45
        ///-23
        ///-41
        ///-85
        ///-2
        ///-90
        ///-31
        ///-47
        ///-81
        ///-40
        ///-43
        ///-51
        ///-61
        ///-41
        ///-64
        ///-60
        ///-5
        ///-29
        ///-18
        ///-104
        ///-70
        ///-68
        ///-53
        ///-17
        ///-58
        ///-107
        ///1
        ///- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day5 {
            get {
                return ResourceManager.GetString("Day5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4	10	4	1	8	4	9	14	5	1	14	15	0	15	3	5.
        /// </summary>
        internal static string Day6 {
            get {
                return ResourceManager.GetString("Day6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hwv inc 149 if clj &gt;= -5
        ///or inc 530 if hwv &gt; 144
        ///d inc 131 if f &lt; 1
        ///gnz dec -236 if jp != 0
        ///mu dec 266 if sp &gt;= -6
        ///t inc -146 if w &gt;= 8
        ///w dec 825 if jp != 3
        ///cto dec 403 if ino != 0
        ///ino inc 17 if sp != 0
        ///bt inc -341 if sp != 6
        ///vv dec 824 if clj &gt;= -9
        ///mu inc -371 if gnz &lt; -7
        ///f dec 865 if w &gt; -828
        ///cto inc 588 if noj == 0
        ///mvh inc 484 if noj == 0
        ///ino inc -728 if gnz &gt; -6
        ///or inc -795 if nm &gt;= -9
        ///q dec -87 if or != -274
        ///q dec -889 if q &gt; 80
        ///f dec 155 if t &lt;= -3
        ///or dec 185 if nm &lt; 9
        ///w inc -243  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day8 {
            get {
                return ResourceManager.GetString("Day8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{{{{{&lt;!!&quot;!!!&gt;},&lt;&gt;},{&lt;o!&gt;},&lt;u!!i!!&apos;!&gt;,&lt;!!!&gt;,e{&apos;e!!!&gt;},&lt;!i&gt;}},{{&lt;&quot;o!!&quot;!&gt;,&lt;&gt;},&lt;!io&lt;&gt;},{{},&lt;!!!&gt;!&gt;,&lt;o&quot;e!&lt;!!!&gt;{,!!!&gt;{a!o,au!&gt;},&lt;&gt;}}},{{{&lt;e!}&gt;},{{&lt;!&gt;,,e!!!&gt;!!,&gt;},{&lt;a!!!&gt;&apos;!!!&gt;!!!!,!!!&gt;!!!&gt;!&gt;},&lt;&lt;{&quot;!!&gt;}},{{&lt;!&gt;&gt;,&lt;!&gt;},&lt;i!&gt;!&lt;&gt;},{&lt;!!&lt;u,a&quot;!&gt;},&lt;o{{!!{!!!&gt;i,!&gt;,&lt;i{!u&gt;,{&lt;a!&gt;e}o!&gt;!&gt;e&gt;}}}},{{&lt;i&lt;!&gt;,&lt;!!!&gt;,&lt;ei,!&gt;a&gt;,{}},{&lt;!!!&gt;},&lt;e&apos;&gt;,{}},{{&lt;!!!!u&lt;,&apos;}!&gt;,&lt;&quot;o&lt;&gt;}}}},{{{{{{&lt;!&gt;,&lt;o!!!auii!!!!!&gt;!!!&gt;,&lt;{&gt;}},&lt;},!!!&gt;!!!!!&gt;&gt;},{&lt;&apos;u&lt;&quot;{&gt;,{&lt;!!!!e!&gt;,&lt;&apos;a!!i&lt;!&gt;,&gt;}},{}},{{&lt;i}&lt;!u&lt;{!!!}!!e!{!,&gt;}},{&lt;!!e,!&gt;i&gt;,{}}},{{&lt;i!!!&gt;},&lt;{&apos;&apos;i!!!&gt;,!e!&gt;},&lt;!&gt;&quot;a{&gt;,&lt;!!&apos;u! [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
    }
}
